### ISSUE TITLE
There is a problem when unzip files larger than 50M

### ISSUE THREAD

**Issue by baizn** [cthackers/adm-zip#108]
Unzip files larger than 50M when synchronization is slow to read the file contents, and generate new ZIP part of the package in question, if the asynchronous read the file contents, how to ensure that the order of files and directory structure?

**Comment by cthackers** [comment]
There now is a async version that you can use to extract large files. The order of the files and directory structure is not important. The zip header contains records with everything inside and can be extracted in whatever order you want.
