### ISSUE TITLE
Unnecessary folder in ./test/

### ISSUE THREAD

**Issue by rictorres** [cthackers/adm-zip#109]
Inside the `./test` folder we have [`attributes_test`](https://github.com/cthackers/adm-zip/tree/master/test/assets/attributes_test).

I might be mistaken but I don't think we need it, in fact it looks like it should have been removed before uploading the module to NPM.

Those folders break my `rpmbuild` script :{

What are your thoughts on this?

**Comment by cthackers** [comment]
the atributes_test contains the files that are compressed in attributes_test.zip with 7Zip and have hidden/read-only and so on attributes, the reason the folder is there is to test that files extracted from the zip match the ones in the folder and vice versa.
There now is a "files" attribute in the package.json that doesn't include the test folder.
