### ISSUE TITLE
Corrupted decompressed binary file

### ISSUE THREAD

**Issue by Befzz** [cthackers/adm-zip#112]
just tryed to decompress 7za920.zip (http://www.7-zip.org/download.html --- 7z command line version)
and its corrupted.

**7za.exe** extracted by 7z is not corrupted.

sizes are the same.
binary comparsion (fc /b 7za.exe 7za_good.exe) show up a lot.

```
Comparing files 7za.exe and 7ZA_good.EXE
0007B9E8: 00 C0
0007B9EF: 00 46
0007B9F0: 00 E0
0007B9F1: 00 CE
....
```

output file is completely zeroed after 0007B9E8

(win 8.1 x64) tryed different node versions.(9-10)

**Comment by 5saviahv** [comment]
Compression / decompression methods are little different now
