### ISSUE TITLE
Specifying 'STORE'

### ISSUE THREAD

**Issue by rtm** [cthackers/adm-zip#116]
TO create epubs, I need to explicitly specify that the magic mimetype file be STOREd, not compressed. I also need somehow to arrange for it to come **first** in the archive. Any way to do that?

**Comment by bigmeech** [comment]
Hi @rtm  
were you able to solve this issue?

**Comment by rtm** [comment]
I am now using jszip, but haven't gotten around to figuring out if it can handle this requirement. Meantime, I am "faking it" by starting with an archive already properly configured, then adding and removing entries.

**Comment by AndrePessoa** [comment]
You can add a function like this at adm-zip

        storeFile : function(/*String*/entryName, /*Buffer*/content, /*String*/comment, /*Number*/attr) {
            var entry = new ZipEntry();
            entry.entryName = entryName;
            entry.comment = comment || "";

            if (!attr) {
                if (entry.isDirectory) {
                    attr = (040755 << 16) | 0x10; // (permissions drwxr-xr-x) + (MS-DOS directory flag)
                } else {
                    attr = 0644 << 16; // permissions -r-wr--r--
                }
            }

            entry.attr = attr;

            entry.setData(content, 0);
            _zip.setEntry(entry);
        }

and update the entry to accept this method force at zipEntry.js 235:


        setData : function(value, method) {
            uncompressedData = Utils.toBuffer(value);
            if (!_isDirectory && uncompressedData.length) {
                _entryHeader.size = uncompressedData.length;
                if( method !== undefined ){
                    _entryHeader.method = method;
                }else{
                    _entryHeader.method = ( _entryHeader.method !== undefined && _entryHeader.method !== null )? _entryHeader.method : Utils.Constants.DEFLATED;
                }
                _entryHeader.crc = Utils.crc32(value);
            } else { // folders and blank files should be stored
                _entryHeader.method = Utils.Constants.STORED;
            }
        }


This may enable you to choice the compress type. I´m not sure if we has more then 0 or 8, but the door is opened.

**Comment by WhiteTusk** [comment]
I have the same problem. I added @AndrePessoa  code but I still get the same error. If I look at the entry, I see that it is the first entry and method=0; Not sure how to tell if it is truly uncompressed, but I assume it is. Not sure what else to try at this point.

**Comment by WhiteTusk** [comment]
Found the answer! In zipFile.js the function compressToBuffer sorts the items in the buffer alphabetically by file name before saving them into the zip.
Change the sort algorithm to the following and it will solve the issue:

        if (entryList.length > 1) {
            entryList.sort(function(a, b) {
                if (a.entryName === "mimetype") {return -1}
                var nameA = a.entryName.toLowerCase();
                var nameB = b.entryName.toLowerCase();
                if (nameA < nameB) {return -1}
                if (nameA > nameB) {return 1}
                return 0;
            });
        }

Note that it relies on your filename being "mimetype" without an extension (which it should be).
