### ISSUE TITLE
simple test but fail, file is zip as folder

### ISSUE THREAD

**Issue by atian25** [cthackers/adm-zip#127]
```
var AdmZip = require('adm-zip');
var zip = new AdmZip();
zip.addFile("test.txt", new Buffer("inner content of the file"), "entry comment goes here");
zip.writeZip('d:/files.zip');
```

![image](https://cloud.githubusercontent.com/assets/227713/6476336/8ba6a5e4-c24f-11e4-877f-72963d11fc3f.png)

**Comment by FKSI** [comment]
Same here!

**Comment by tomercagan** [comment]
I see the same as well

**Comment by Danjavia** [comment]
Same issue here! Help.

**Comment by zxc122333** [comment]
Same here! 
Ping @cthackers

**Comment by WhiteAbeLincoln** [comment]
same issue

**Comment by tobaiasjl** [comment]
same issue

**Comment by token97** [comment]
Same issue. 
After several test, I saw that if I compress and decompress files using adm-zip,  the result is good, but I can't decompress archive using 7-Zip, Winrar or other. Then we can't share the zip file.
They are maybe a problem in the compression process.

**Comment by Bersam** [comment]
same problem here.

**Comment by marcelboettcher** [comment]
same here with addLocalFile. Btw. zip file size is correct, but objects are just folders.

**Comment by YanaSavchenko** [comment]
+1

**Comment by token97** [comment]
I finally use [node-archiver](https://github.com/archiverjs/node-archiver). It's a other zip project that works very well.
have fun

**Comment by Danjavia** [comment]
+1 @token97

**Comment by m4rcelofs** [comment]
+1

**Comment by WiR3D-kNiGhT** [comment]
still a problem, almost a year later

**Comment by qhoffman** [comment]
_Still_ an issue.

Really unfortunate.

**Comment by ystreibel** [comment]
+1

**Comment by alexayan** [comment]
+1

**Comment by benkaiser** [comment]
This worked for `addLocalFile` in 0.4.4 but is broken in 0.4.7

See screenshot when unzipping respective folders using file-roller:
![image](https://cloud.githubusercontent.com/assets/608054/14605182/c634a71a-05ba-11e6-93c0-e07b2beabf2e.png)
