### ISSUE TITLE
Wrong compression with binary content

### ISSUE THREAD

**Issue by nicolapiccinelli** [cthackers/adm-zip#133]
Hi, i'm using adm for a web service (clippy.cc). We are having trouble with decompression of the archive created in memory using the buffer. Right now i've solved the issue changing in the source code a default parameter in the setData function from DEFLATE to STORED.

That's the code used [source](http://www.clippy.cc/directaccess/d2b92a365b3e3e65c5c443a67740cc1b), when there is an entry as binary i got a corrupted archive.

**Comment by christav** [comment]
I'm seeing this as well - creating a zip file, adding files use addLocalFile, when trying to uncompress with info-zip I get error:  invalid compressed data to inflate on most, but not all, of the binary files in the archive.

Win 8.1, node 0.12.2.

**Comment by paulhayes** [comment]
I'm seeing this too, using any technique. I'm unable to inflate binary files from zip files created by ADM. Tried both toBuffer() or writeZip(), AddLocalFile and AddLocalFolder all had the same results. 

Such a shame I'm going to have to switch libraries. I love the style of this one, and the fact it is all synchronous is a plus for me as I'm writing some batch operations.

**Comment by nicolapiccinelli** [comment]
Maybe if someone of us have time to investigate on it we will be able to fix and make a pull request or maybe if the owner is off we can fork adm-zip.

**Comment by paulhayes** [comment]
yeah, I'm guessing it's since nodejs v0.12. As I just updated today. But
don't take my word for that.

**Comment by Prior99** [comment]
I can also confirm this with node v0.12.
CRC's do not match, files are corrupted or have invalid code lengths.
