### ISSUE TITLE
Created zip files have CRC errors (again)

### ISSUE THREAD

**Issue by jcwren** [cthackers/adm-zip#144]
I previously posted this fix, which addresses the issue of files within the zip having a bad CRC. I thought it had been applied, but it appears to never have actually been applied, or it got reverted at some point.

``` javascript
File util/utils.js: 71c71
<             while(--len >= 0) c1 = crcTable[(c1 ^ buf[off++]) & 0xff] ^ (c1 >>> 8);

---
>             while(--len >= 0) c1 = crcTable[(c1 ^ buf[off++].charCodeAt()) & 0xff] ^ (c1 >>> 8);
```

**Comment by jcwren** [comment]
Actually, the fix is in the repository, but version 0.4.8 has never been pushed. The latest version is 0.4.7, which was released one day before the change was applied. Can you push 0.4.8, please?

**Comment by danopia** [comment]
+1 This bit me today

**Comment by danopia** [comment]
...or not because master errors instead:

```
TypeError: undefined is not a function
  at Object.module.exports.crc32 (/tmp/deployer/node_modules/adm-zip/util/utils.js:71:62)
  at Object.setData (/tmp/deployer/node_modules/adm-zip/zipEntry.js:234:42)
  at Object.addFile (/tmp/deployer/node_modules/adm-zip/adm-zip.js:290:19)
  at buildZip (/tmp/deployer/deploy.coffee:19:7)
```
