### ISSUE TITLE
Licensing issues MIT vs GPL

### ISSUE THREAD

**Issue by dmartinezg** [cthackers/adm-zip#145]
Hi, while the library claims to be MIT (https://github.com/cthackers/adm-zip/blob/master/MIT-LICENSE.txt), it contains code licensed under the GPL in the deflated module (https://github.com/cthackers/adm-zip/blob/master/methods/deflater.js).

While IANAL, this is highly irregular, deflater.js should be re-implemented so that it can be licensed under  MIT, or the project should be re-licensed under GPL.

**Comment by guillaume-d** [comment]
Duplicate of #77 which is older and has more info, please delete this.

**Comment by dmartinezg** [comment]
I'll close it, but please address the issue.
