### ISSUE TITLE
extractEntryTo is not working

### ISSUE THREAD

**Issue by ankitgo** [cthackers/adm-zip#147]
Extracting a folder fails with the following error (though extracting files work fine)

D:\githubadmzip\adm-zip\adm-zip.js:339
                throw Utils.Errors.NO_ENTRY;
                                  ^
Entry doesn't exist.

I debugged this a little, the entryTable doesn't have entries for folders, only for files are available.

**Comment by zecoenergy** [comment]
Just for others with the same issue, I encountered this issue too however it was because I used `entry.name` instead of `entry.entryName` or even just the entry it self.

i.e.

    myZip.extractEntryTo(entry.entryName, 'path-to-folder', false, true);

or

    myZip.extractEntryTo(entry, 'path-to-folder', false, true);

HTH?

**Comment by 5saviahv** [comment]
same as #414 & #419
