### ISSUE TITLE
Error when zipping using addLocalFolder()

### ISSUE THREAD

**Issue by gauravdhiman** [cthackers/adm-zip#152]
I am using it as below to zip the folder and files / sub-folders under it:

```
var AdmZip = require('adm-zip');
var zip = new AdmZip();
zip.addLocalFolder(folderPath, path2zip + '/' + file + '.zip');
zip.writeZip(path2zip + '/' + file + '.zip');
```

Getting below error. If you have any workaround, kindly share. Also a request to update the package in NPM. 

```
node_modules\adm-zip\util\utils.js:71
            while(--len >= 0) c1 = crcTable[(c1 ^ buf[off++].charCodeAt()) & 0
                                                             ^
TypeError: undefined is not a function
    at Object.module.exports.crc32 (node_modules\adm-zip\util\utils.js:71:62)
    at Object.setData (node_modules\adm-zip\zipEntry.js:234:42)
    at Object.addFile (node_modules\adm-zip\adm-zip.js:290:19)
    at node_modules\adm-zip\adm-zip.js:253:38
    at Array.forEach (native)
    at Object.addLocalFolder (node_modules\adm-zip\adm-zip.js:249:27)
```

**Comment by ealfonsov89** [comment]
me to

**Comment by FilipPyrek** [comment]
I have same problem... PLEASE somebody who understand ZIPs, fix it. Thank you very much! :)

**Comment by francispelland** [comment]
Ditto on having this problem.

**Comment by bhumikVa-kore** [comment]
@gauravdhiman did you get something on it

**Comment by gauravdhiman** [comment]
@bhumikVa-kore .. no update on it.

**Comment by teikblade** [comment]
A mi me funciono asi uso nodejs con express 
router.get('/download/:id', (req, res) => {
 zip.addLocalFile(path.join(dirContent.dir+'/public/css/'+req.params.id))
 zip.writeZip(path.join(dirContent.dir+'/public/downloads/tmp/test.zip'));
})

**Comment by 5saviahv** [comment]
It seems to have crc error and is fixed
