### ISSUE TITLE
Files with leading ./ not found

### ISSUE THREAD

**Issue by periloso** [cthackers/adm-zip#155]
I am trying to extract a file from the top directory in the zip file; however, if there's a leading ./ to the path, the file won't be found.

Ex.:
- zip file with the file "README.txt" inside it
- extracting "README.txt" will work
- extracting "./README.txt" will not work.

(version 0.4.7)

**Comment by aesopwolf** [comment]
This might be because of `readdirSync`

> Synchronous readdir(3). Returns an array of filenames excluding '.' and '..'. 

https://nodejs.org/api/fs.html#fs_fs_readdirsync_path
