### ISSUE TITLE
"bad CRC" error when unzipping

### ISSUE THREAD

**Issue by bendytree** [cthackers/adm-zip#156]
I'm on node `0.10.28` and adm-zip `0.4.7`. I'm adding buffers to the zip like this:

```
zip.addFile("font-awesome.min.css", buffer);
...
zip.toBuffer(success, fail);
```

Once I save the zip, I'm unable to unzip it on WinRAR and Android. I can see errors on my mac if I run:

```
> unzip -tq myzip.zip
font-awesome.min.css    bad CRC 431e7486  (should be 1c59b6fc)
layout-browserify.min.js  bad CRC 246ae7f0  (should be e1023c15)
...etc...
```

Unzipping works on mac, iPhone, and google docs. 

[Here is the original, busted zip file](https://dl.dropboxusercontent.com/u/2505719/myzip.zip)

**Comment by nleclerc** [comment]
I get the same kind of problem with v0.4.7 on node 0.12.9.
Unable to extract content of the archive on OSX 10.11.2.

**Comment by vitalets** [comment]
also having this issue on osx. Does anybody solved it?

**Comment by FilipPyrek** [comment]
It looks, that @cthackers tried to fix it, but current repo is broken. (#152)

**Comment by 5saviahv** [comment]
It seems to be fixed now
