### ISSUE TITLE
Can't zip up folders with underscores in it

### ISSUE THREAD

**Issue by nquinn721** [cthackers/adm-zip#178]
When I zip up folders with underscores in it it seams to corrupt the zip and I can't unzip afterwards.
I tried this with node_modules and separately with bower_components. It seams to work with everything else. I'm using a mac.

When I try to unzip it just says "Unable to expand 'zip.zip' into 'folder/' (Error 2 - no such file or directory)"

**Comment by kampfgnu** [comment]
+1

**Comment by cherish1260** [comment]
Did you resolve this problem？I have same problem
