### ISSUE TITLE
entryHeader.js shows wrong date in header. 

### ISSUE THREAD

**Issue by ShankzPatil** [cthackers/adm-zip#179]
function setTime(val) {
        var val = new Date(val);

        _time = (val.getFullYear() - 1980 & 0x7f) << 25  // b09-16 years from 1980
            | (val.getMonth() + 1) << 21                 // b05-08 month
            | val.getDate() << 16                             // b00-04 hour

            // 2 bytes time
            | val.getHours() << 11    // b11-15 hour
            | val.getMinutes() << 5   // b05-10 minute
            | val.getSeconds() >> 1;  // b00-04 seconds divided by 2
    }

use .getDate instead of .getDay.

The value returned by getDay is an integer corresponding to the day of the week: 0 for Sunday, 1 for Monday, 2 for Tuesday, and so on.

**Comment by teppeis** [comment]
@cthackers closed with #203?

**Comment by ShankzPatil** [comment]
great
