### ISSUE TITLE
Zipping files as directories

### ISSUE THREAD

**Issue by bpavlov** [cthackers/adm-zip#182]
Adm-zip version: 0.4.7
Node version: 4.3

Zip file created via multiple invocation of addFile(entryName, content, comment, attr) function, contains folders instead of files  

![image](https://cloud.githubusercontent.com/assets/2480572/23752820/90c9c482-04df-11e7-83e0-982250b4f742.png)

This was seen also in issue #22

**Comment by mintyPT** [comment]
I have the same issue. The weird part is when I open the zip on a mac, it's ok; if I open it on windows or linux, then my files turn to directories.

**Comment by kryo2k** [comment]
Same issue here too.

**Comment by mintyPT** [comment]
I never zip folders, only files and went looking at the function I was calling.

`addFile : function(/*String*/entryName, /*Buffer*/content, /*String*/comment, /*Number*/attr) {
            var entry = new ZipEntry();
            entry.entryName = entryName;
            entry.comment = comment || "";

            if (!attr) {
                if (entry.isDirectory) {
                    attr = (040755 << 16) | 0x10; // (permissions drwxr-xr-x) + (MS-DOS directory flag)
                } else {
                    attr = 0644 << 16; // permissions -r-wr--r--
                }
            }

            entry.attr = attr;

            entry.setData(content);
            _zip.setEntry(entry);
        },
`


To solve (bypass) my problem, I simply passed the _attr_ argument when calling the function

**Comment by niczak** [comment]
To get around this issue I did the following:

```
var zip = new ADMZip();
var input = fs.readFileSync(pathToCSV);
zip.addFile('file_name_here.csv', input, '', 0644);
zip.writeZip(pathToZip);
```
^--- This works on both OSX and Windows.

**Comment by mattflix** [comment]
@niczak's workaround can't be applied when using addLocalFolder(), since it calls addFile() for you.

Workarounds are nice, but this is just plain broken.

**Comment by DaveyD** [comment]
I have the same problem
Using addLocalFile results in creating an empty directory for each file
Using @niczak workaround works, however in Windows Explorer it shows an empty directory (but the size of it is what it should be with all the files in it). In Total Commander, it shows as files with a red exclamation point on it.

In short, the addFile and addLocalFile seem to be broken

**Comment by filipelautert** [comment]
Going back to 0.4.6 fixed this issue for me.

**Comment by mattflix** [comment]
@filipelautert, I can't install 0.4.6 under Windows -- npm gives a bunch of Python errors that don't occur when installing 0.4.7.   *shrug*

**Comment by mcnach** [comment]
Same problem here. I'll try to use 'archiver' instead.
