### ISSUE TITLE
0x80004005 error while extracting the zip file

### ISSUE THREAD

**Issue by subhashmatta** [cthackers/adm-zip#188]
Getting 0x80004005 error while extracting the files. I am passing 0644 as fourth parameter(attr) to addFile method.

            data.forEach(function (rec) {
                zip.addFile(rec.name + ".json", JSON.stringify(rec.records, 0, 2), '', 0644);
            });
            var data = zip.toBuffer();
            cb(null, data, 'application/octet-stream', 'attachment; filename=metdata.zip');

I am not using any 7zip or winrar to extract. (using default window extract tool)
May work for 7zip or winrar software, and working while extracting from online tools.

Kindly guide me through this issue.

**Comment by 5saviahv** [comment]
I assume it was crc error

**Comment by chalkiasS** [comment]
Hello @subhashmatta I had the same error and it turns out it has to do with special characters in the filenames. My file names had dashes, dots, etc. and this would occur everytime. Try filenames that don't have these characters.
