### ISSUE TITLE
I see no callback in API, is this an I/O sync lib?

### ISSUE THREAD

**Issue by benpptung** [cthackers/adm-zip#201]
Only see fs.readFileSync in source code of `addFile()`, and wondering this is an I/O sync lib.

I need to bundle couple of files into a zip file, wondering how to do it async I/O using these API.

**Comment by ianldgs** [comment]
I was with the same doubt. Checked the code, it's all written with blocking operations.
After a few hours of research, found this lib: https://github.com/node-modules/compressing, with more modern code and with suport for everthing in compressing

**Comment by andresilvasantos** [comment]
@ianldgs That's a great find! I've tested it and it works flawlessly. Thank you!
