### ISSUE TITLE
fs.existsSync not a function error

### ISSUE THREAD

**Issue by nityanandagohain** [cthackers/adm-zip#207]
I am getting a error while trying to use this library in my angular electron app . Please help

**Comment by Arkellys** [comment]
Is there a fix for that? I have the same problem with an Electron + React (CRA) app...

**Comment by Arkellys** [comment]
In case someone else as the same problem, I fixed it by adding `target: 'electron-renderer';` on my webpack config.

**Comment by gefeiyanga** [comment]
Can you talk specifically
