### ISSUE TITLE
Error in require in version 0.4.8

### ISSUE THREAD

**Issue by tavarest** [cthackers/adm-zip#213]
After updating to version 0.4.8 it is not possible to use the package in React due to the following error:

`./node_modules/adm-zip/util/fileSystem.js
Module not found: Can't resolve 'original-fs' in '...\node_modules\adm-zip\util'`

I believe it is because in util (fileSystem.js) it is trying to require"original-fs" (which is only available in Electron) instead of just requiring fs. This makes it impossible to use the package when using React.

With the previous version (0.4.7) everything works fine.

**Comment by kspearrin** [comment]
Was this fixed? Still seeing this in 0.4.11.

**Comment by alexkli** [comment]
Seeing this as well in 0.4.11, reported again as #242.

**Comment by lechuhuuha** [comment]
still errro in ^0.5.9
