### ISSUE TITLE
AdmZip#toBuffer() leads to RangeError [ERR_INVALID_OPT_VALUE]

### ISSUE THREAD

**Issue by Thorsten-SCE** [cthackers/adm-zip#218]
Hi,

starting with version **0.4.8** I get the following error with AdmZip#toBuffer():

**RangeError[ERR_INVALID_OPT_VALUE]:** The value "2884517930" is invalid for option "value".

Up to version **0.4.7** it worked excellently. Enclosed a Typescript code snippet.
[adm-zip-error.zip](https://github.com/cthackers/adm-zip/files/1954204/adm-zip-error.zip)

Thank you
Thorsten

**Comment by jeremytm** [comment]
This issue has hit us too.

**Comment by jmcollin78** [comment]
Same with 0.4.9. Any hints to bypass this ?

**Comment by jmcollin78** [comment]
Ok, I found a solution (or a workaround ?!)
Just edit the line 216 of headers/entryHeader.js and change to this line:

`data.writeUInt32LE(_crc, Constants.CENCRC);`

instead of `data.writeInt32LE(_crc, Constants.CENCRC);`

Notice the U in write**U**Int32LE

For me it fixes the bug.
I've got not time to make a PR, but I hope a contributor can push this change quickly.

Jean-marc

**Comment by mfrancois** [comment]
Same issue on my project.

**Comment by jmcollin78** [comment]
hi @mfrancois , did you try the fix explains above ? Did that solve your problem ?

**Comment by mfrancois** [comment]
Hi @jmcollin78 ,
I did test it can I wouldn't change the node_module file. Actually I change package from adm-zip to node-archive, another good one.

**Comment by jmcollin78** [comment]
@mfrancois I understand. I have the idea to switch too, but this module is the only which can zip and unzip. In my case, i need both feature. I will wait a few for contributors before switching ...

**Comment by jmcollin78** [comment]
Here you will find a fork that is fixing the issue: https://github.com/jmcollin78/adm-zip

it is published with the following name: 

`npm install adm-zip-jmcnet`

**Comment by Thorsten-SCE** [comment]
Issue is solved with version 0.4.11

Thanks to all 👍
