### ISSUE TITLE
Node.js example contains zipped folder instead of file

### ISSUE THREAD

**Issue by Bartvds** [cthackers/adm-zip#22]
For me the node.js compression example on ''ADM-ZIP-Introduction' on the wiki produces readable zip but with an empty folder named 'test.txt' instead of the 'test.txt' file.

I got adm-zip from npm today, it's package.json says 0.1.8 and this was on windows vista 64bit, my node.js is 0.8.14 x64 and I unzip using good ol' WinRar.

My code:

```
var zip = new Zip();
zip.addFile("test.txt", new Buffer("inner content of the file"), "entry comment goes here");    
zip.writeZip(path + '/package.zip');`
```

**Comment by mordka** [comment]
Same problem with `0.4.7`

**Comment by kryo2k** [comment]
+1 still having this issue on 0.4.7
