### ISSUE TITLE
unzip output is flattened in windows

### ISSUE THREAD

**Issue by YounGoat** [cthackers/adm-zip#220]
In version 0.4.9, entry name will be escaped in Windows:

```javascript
function escapeFileName(/*String*/filename){
    return filename.replace(/[\:,\/,\>,\<,\",\\,\|,\?,\*"]/g, '_');
}
```

Unfortunately, because slash / is also replaced with underscore _, the output will be flattened without any directories reserved.

**Comment by nonoroazoro** [comment]
Me too on window (win 7), while mac is OK.
