### ISSUE TITLE
No error stack trace if given an invalid path to unzip

### ISSUE THREAD

**Issue by tejashah88** [cthackers/adm-zip#236]
If you give it an invalid path, there isn't a stack trace to show that this is the problem causing my app to seemingly crash without any reason. I spent 4 hours trying to figure out why it was crashing for seemingly no reason.

Error log:
```bash
error: uncaughtException: Invalid filename
  No stack trace {"error":"Invalid filename","exception":true,"date":"Tue Jun 12 2018 00:13:37 GMT-0700 (Pacific Daylight Time)","process":{"pid":166656,"uid":null,"gid":null,"cwd":"C:\\Users\\<user>\\projects\\node-apps\\sample_app","execPath":"C:\\Users\\<user>\\scoop\\apps\\nodejs\\current\\node.exe","version":"v10.4.0","argv":["C:\\Users\\<user>\\scoop\\apps\\nodejs\\current\\node.exe","C:\\Users\\Tejas\\projects\\node-apps\\sample_app\\src\\index"],"memoryUsage":{"rss":67510272,"heapTotal":57692160,"heapUsed":36605584,"external":2202082}},"os":{"loadavg":[0,0,0],"uptime":198502},"trace":[]}
```
\* \<user\> is my redacted username and "sample_app" is the working directory of the app

To reproduce, just make a zip file, make an invalid path and it should give a similar response to the above error log.
```javascript
var entries = new AdmZip(invalidFilePath).getEntries();
console.log(entries);
```

This was testing on Node.js version 10.4.0 on Windows 10.

**Comment by mattsains** [comment]
I have come across the same problem. I think it's because the library is throwing raw strings as exceptions, eg: https://github.com/cthackers/adm-zip/blob/master/util/errors.js and https://github.com/cthackers/adm-zip/blob/ff17ae85000b62b9d159e2520564902724d26c17/headers/entryHeader.js#L140

@cthackers would it be ok if I do a PR to turn those strings into Error instances?

**Comment by tejashah88** [comment]
@mattsains Thanks for the PR!
