### ISSUE TITLE
License file missing in npm package

### ISSUE THREAD

**Issue by char0n** [cthackers/adm-zip#245]
Hello, is it possible to incorporate the LICENSE file inside the npm package ? Now it's missing. It's implied by MIT license that if licensed under the MIT the source code must be accompanied by full license text. If the license file is not in the npm package a lot of people cannot use it (technically nobody).

Thank you

**Comment by 5saviahv** [comment]
It seems to be fixed now

**Comment by char0n** [comment]
Yep I can confirm, license is in npm package now. Thanks!
