### ISSUE TITLE
Illegal token during npm install with node v0.10.32

### ISSUE THREAD

**Issue by hcburca** [cthackers/adm-zip#283]
I am working on a nodejs repo that uses node `0.10.32`. I would like to add adm-zip as a dependency, but `npm install` breaks with the following error: 
```
/Users/horia.burca/my-project/node_modules/cldr-data/node_modules/cldr-data-downloader/node_modules/adm-zip/adm-zip.js:302
attr = (0o40755 << 16) | 0x10; // (permissions drwxr-xr-x) + (MS-DOS dire
        ^
SyntaxError: Unexpected token ILLEGAL
```
The node engines you support are `>=0.3.0` so normally this should work for `0.10.32`. 
I think the problem lies in the usage of octal values which by looking [here](https://node.green/#ES2015-syntax-octal-and-binary-literals-octal-literals) don't seem to be supported by node versions under `0.12.18`.
Is it possible to make this compatible with all `>=0.3.0` node engines?

**Comment by 5saviahv** [comment]
this >=0.3.0 is misleading, code uses heavily Buffers alloc() and from() functions. So minimum should be probably `v4.5.0`.

`0o40755` is actually ES6-style octal literal - not sure is it compatible with `v4.5.0` ?
