### ISSUE TITLE
[VERSION] Release new version with last commit

### ISSUE THREAD

**Issue by v4l3r10** [cthackers/adm-zip#289]
There are many useful commit on the master branch. It's the time of new version for adm-zip :)

**Comment by ozelot379** [comment]
I had also some bugs which is already fixed on github but not on npm

I used the follow workaround in `package.json` > `dependencies` to use the latest version from github:
```json
"adm-zip": "https://github.com/cthackers/adm-zip/tarball/master",
```

**Comment by curran** [comment]
It appears that this package is no longer maintained.

Can anyone recommend an alternative package with similar functionality? Or, is there an active fork with the recent changes published to NPM? Thanks!

**Comment by aizigao** [comment]
same problem in version 0.4.13
can you publish it :smile:

**Comment by steelerc69** [comment]
@cthackers Can you create a new npm or promote ownership to one of the active maintainers?  

Thanks for the awesome package.

**Comment by Arkellys** [comment]
I think it's done? The current version on npm is `0.4.14`
