### ISSUE TITLE
extractAllTo unable to distinguish file name from case

### ISSUE THREAD

**Issue by caoqiang250** [cthackers/adm-zip#291]
extractAllTo('target path',true) unable to distinguish file name from case 
The zip file contains / A / car1_music. h target directory contains / A / car1_Music. H. After decompression, the target directory still contains only car1_Music. h file.

**Comment by 5saviahv** [comment]
Hmmm ... windows file system wont distinguish filenames with different casing. Even when we try write in file with capital .H , but if folder contains file with .h - content is written there.

Option would be delete old file before write or rename it after write.
