### ISSUE TITLE
Request for release the newest version...

### ISSUE THREAD

**Issue by Herffin** [cthackers/adm-zip#298]
Adm-zip is the best package for zip handling. I used it in my nodejs project and finish my function easily! However, when i want to publish my project, my company rejects me because there is no release version in github. **So, can you release the newest version in github?** I don't want to change my zip handler because adm-zip is so easy for developers!

**Comment by Arkellys** [comment]
Duplicate of https://github.com/cthackers/adm-zip/issues/289
