### ISSUE TITLE
extractAllTo not giving the callback once the extraction finished

### ISSUE THREAD

**Issue by mithuns14** [cthackers/adm-zip#305]
extractAllTo not giving the callback once the extraction finished

**Comment by jingyuLin1999** [comment]
I get the same trouble. How to resolve it?

**Comment by Arkellys** [comment]
`extractAllTo` is not made to return a callback:
https://github.com/cthackers/adm-zip/blob/master/adm-zip.js#L513

I think what you want is `extractAllToAsync` instead? It takes a callback as third parameter.
