### ISSUE TITLE
filename or path contains chinese  characters

### ISSUE THREAD

**Issue by 183181731** [cthackers/adm-zip#332]
when filename or path contains chinese characters，the output zip file  file name issue
Code:
var dic = /*my dic path*/
var zip = /*my zip path*/
var zip = new AdmZip();
zip.addLocalFolder(dic);
zip.writeZip(zip);
![image](https://user-images.githubusercontent.com/16742949/100048788-abd42300-2e50-11eb-8c50-1ba55c771a91.png)

**Comment by 5saviahv** [comment]
Can you try this.

```
#!/usr/bin/env node

var AdmZip = require('adm-zip');
var fpp = require('path');

function packer(folder, filepath){
    var zip = new AdmZip();

    zip.addLocalFolder(fpp.join(__dirname,folder));

    // update file headers
    zip.getEntries().forEach(entry => {
        entry.header.flags |= 0x0800;                                          // Set bit 11 - APP Note 4.4.4 Language encoding flag (EFS)
    });

    // save file (we generate our content again)
    zip.writeZip(fpp.join(__dirname,filepath));

}

packer('./packme','./測試文件.zip');
```
It seems to working:

![Screenshot from 2020-11-24 11-08-58](https://user-images.githubusercontent.com/49443574/100073104-be952a80-2e45-11eb-8431-59cdf2931d6c.png)

**Comment by 183181731** [comment]
@5saviahv thanks!! it can work for me

**Comment by onsummer** [comment]
Thanks! It work.

For the convenience of future people, I put my code up:

``` js
// pre
const zip = new AdmZip()
zip.addLocalFolder("dist/")
zip.writeZip(`dist/macao-${serverName}-${getTimeTag()}.zip`)
```

``` js
// after
const zip = new AdmZip()
zip.addLocalFolder("dist/")
zip.getEntries().forEach((entry) => {
  entry.header.flags |= 0x0800
})
zip.writeZip(`dist/macao-${serverName}-${getTimeTag()}.zip`)
```

**Comment by 5saviahv** [comment]
It should be default behaviour for now
