### ISSUE TITLE
Range error with bigger zipfile > 2GB

### ISSUE THREAD

**Issue by janneman001** [cthackers/adm-zip#334]
RangeError [ERR_FS_FILE_TOO_LARGE] when trying to get entries of bigger zipfile:

File size (2653263820) is greater than possible Buffer: 2147483647 bytes
    at tryCreateBuffer (fs.js:318:13)
    at Object.readFileSync (fs.js:354:14)
    at new module.exports (/node_modules/adm-zip/zipFile.js:18:17)
    at new module.exports (/node_modules/adm-zip/adm-zip.js:20:11)

**Comment by 5saviahv** [comment]
Yes, adm-zip reads entire file into memory and holds it there. Currently there is no workarounds from it.

**Comment by cainsyake** [comment]
Can this limit be configured?

**Comment by 5saviahv** [comment]
I am not sure about it, but you can check it, limitation comes from `buffer.kMaxLength`.

**Comment by janneman001** [comment]
i replaced the module with node-stream-zip since i only needed an entry from the zip directory uncompressed size and this module reads blocks as it goes, not the whole file at once. Thanks for the replies.

**Comment by duterte** [comment]
I encounter the same Issue with this. Too bad, cause this Issue was close without any presented solution.

**Comment by HeldaKalak** [comment]
I did the same like @janneman001. Its working now.
refrence: https://github.com/antelle/node-stream-zip

 const zip = new StreamZip({
    file
  });
  zip.on("error", (err) => {
    throw Error(err);
  });

  zip.on("entry", (entry) => {
    //do what you want.
    console.log(entry.name);
    }
  });

  zip.on("ready", () => {
    zip.extract(null, outputPath, (err) => {
      if (err) {
        throw new Error(err);
      }
      zip.close();
    });
  });
