### ISSUE TITLE
zip.extractEntryTo outFileName parameter not handled correctly if not set

### ISSUE THREAD

**Issue by elpollouk** [cthackers/adm-zip#335]
**Repro steps:**
* Call `extractEntryTo` without specifying `outFileName`, e.g. `zip.extractFileTo(entry, ".", false, true);`

**Expected result:**
File should be extracted to `targetPath` with the name from the entry.

**Actual result:**
Exception thrown in `sanitize` due to attempting to split an `undefined` value.

**Cause:**
The check on line 475 is only checking for an empty string and not nullish values. The check should probably be `!!outFileName`.

**Comment by 5saviahv** [comment]
I understand, since `outFileName` is not defined it value is `undefined` and for sure it is not equal with string `""`

**Comment by elpollouk** [comment]
Is this a backwards compatibility issue as it's a new parameter to an existing function? Pre-existing code calling this function will start throwing exceptions after picking up this update.

**Comment by 5saviahv** [comment]
This parameter was added there for request, but for backward compatibility it obviously has to accept this method without this parameter.

This method is actually in testing routine and last build failed and reason is in this method.
```
zip.extractEntryTo(entry, destination, false, true):
TypeError: Cannot read property 'split' of undefined
at sanitize (adm-zip.js:32:20)
at Object.extractEntryTo (adm-zip.js:474:17)
at Array.forEach (<anonymous>)
at next (node_modules/rimraf/rimraf.js:69:7)
at CB (node_modules/rimraf/rimraf.js:100:9)
at FSReqCallback.oncomplete (node:fs:179:23)
```

**Comment by elpollouk** [comment]
Just picked up version 0.5.1 and `extractEntryTo` is working as expected. Thanks very much!
