### ISSUE TITLE
getEntries returns empty array

### ISSUE THREAD

**Issue by kyledecot** [cthackers/adm-zip#338]
When attempting to get the entries of an S3 object (zip w/ various `.js`, `.css`, etc files) I am receiving empty array–I am using version `0.5.0`.

```
  ...
  const buffer = s3.getObject({
    Bucket: s3Bucket,
    Key: s3Key
  }).createReadStream();

  const zip = new AdmZip(buffer);
  const zipEntries = zip.getEntries();

  console.log('zipEntries', zipEntries)
```

**Comment by cthackers** [comment]
It doesn't read the stream. The zip header is at the end of the file. So you need to wait to open it as zip until the stream is done on 'end' event.
