### ISSUE TITLE
Missing CHANGELOG

### ISSUE THREAD

**Issue by medikoo** [cthackers/adm-zip#340]
I'd love to learn what changed with v0.5, but there's no changelog provided.

Were there any breaking changes? Is it safe to upgrade?

I know I can inspect diff of code changes, but that's by no means convenient and doesn't give solid picture

**Comment by 5saviahv** [comment]
I looked changes in 0.4.16 - 0.5.1

* minimum node version is 6.0 - it uses const, let variables
* **addLocalFile** reads file attributes and adds it with file data to zip file
* **addLocalFolder** filepaths is handled with path.relative no longer regexp
* **extractEntryTo** is additional parameter for renaming file
* using deflate method sets minimum extraction version to pkzip v2.0 (according to zip specs)
* multibyte comment is correctly written to file
* added **zipcrypto** extraction ability
* **LICENSE** file is now add with package
* better support for browser environments 
* project got tagged by npm versions

**Comment by medikoo** [comment]
Thanks @5saviahv still it doesn't solve the issue for the feature versions. I believe a proper CHANGELOG has to be setup

**Comment by 5saviahv** [comment]
Library is open-sourced and you are always welcome to make PR
