### ISSUE TITLE
Permission lost after unzipping using `extractAllTo`

### ISSUE THREAD

**Issue by timqian** [cthackers/adm-zip#342]
After unzipping this zip file: ([test.sh.zip](https://github.com/cthackers/adm-zip/files/5827869/test.sh.zip)), the file is no longer an executable program.

### Code

```js
const AdmZip = require('adm-zip');

const zip = new AdmZip('./test.sh.zip');
zip.extractAllTo('./tempFolder', true);
```
#### Before `extractAllTo`

```bash
> zipinfo test.sh.zip 
-rwxrwxrwx  2.0 unx       23 bX defN 21-Jan-18 12:24 test.sh
```

#### After

```bash
> ls -al tempFolder/test.sh 
-rw-rw-rw-  1 timqian  staff  23 Jan 18 12:24 tempFolder/test.sh
```

**Comment by eahefnawy** [comment]
@timqian is that still an issue after mering https://github.com/serverlessinc/platform/pull/268?

**Comment by timqian** [comment]
@eahefnawy Yeah, this is an issue that happens when downloading and unzipping folders

**Comment by timqian** [comment]
This bug is fixed in this commit https://github.com/cthackers/adm-zip/commit/ec79116ed5d22ed998f55d18fa0e051da22a9fb9
