### ISSUE TITLE
Security Issue: Request for contact

### ISSUE THREAD

**Issue by pwntester** [cthackers/adm-zip#343]
Hello,

The GitHub Security Lab team has found a potential vulnerability in your project. Please create a Security Advisory and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a Security Policy containing a security email address to send the details to.

Kind regards,
A

**Comment by cthackers** [comment]
Hi @pwntester. I just pushed a fix for this issue. 119dcad
Thanks for the report.
