### ISSUE TITLE
No longer being able to send Buffer to constructor

### ISSUE THREAD

**Issue by ggarcia24** [cthackers/adm-zip#358]
Before v0.5.4 I could write the following code:

```
const zipFile = new AdmZip(Buffer.from(fileContent, 'base64'));
zipFile.getEntries().forEach(entry => {
   console.log(entry);
});
```

This option is no longer available due to the [check in the code](https://github.com/cthackers/adm-zip/blob/master/adm-zip.js):

```
if (input instanceof Uint8Array){
```

Is there any way that I could read a zip file comming as a Base64 string with the new version?

Best regards
Gonzalo G

**Comment by 5saviahv** [comment]
Just for curiosity what is the node version where you use it.

**Comment by 5saviahv** [comment]
It does work with buffers in my Node 12.

**Comment by ggarcia24** [comment]
I'm using Node v12.20.2, I will try later to write a bit of code that might help

**Comment by 5saviahv** [comment]
it would be greatly appreciated if you can share some code please.

**Comment by tejodorus** [comment]
Hello, I also experience this issue. It also occurs after upgrading from node12 to node 14. Apparently, the Buffer objects are not "instanceof Uint8Array".

Why the change to this check, instead of the original check (Buffer.isBuffer)? It seems that that function is intended for this use case?

**Comment by AllanDaemon** [comment]
This code worked for me and even helped to figure out how to load a file from a base64 string (something I couldn't with the documentation).

**Comment by 5saviahv** [comment]
Many cases Buffer is Uint8Array, but apparently not always, so I reverted Uint8Array check.

**Comment by david-mohr** [comment]
Thanks @5saviahv , I was having the same issue and this fixes it. Do you have plans for a 0.5.6 release containing this patch?
