### ISSUE TITLE
Use buffer.from instead of buffer.alloc

### ISSUE THREAD

**Issue by beevelop** [cthackers/adm-zip#367]
The examples in the README make use of `buffer.alloc` and `.length` to create the respective buffers. This might result in issues if the respective string contains special characters. See the bare minimum example down below:
```
> "hallo äöü".length
9
> Buffer.from("hallo äöü", "utf-8").length
12
> Buffer.alloc("hallo äöü".length, "hallo äöü")
<Buffer 68 61 6c 6c 6f 20 c3 a4 c3>
> Buffer.from("hallo äöü", "utf-8")
<Buffer 68 61 6c 6c 6f 20 c3 a4 c3 b6 c3 bc>
> Buffer.alloc(12, "hallo äöü")
<Buffer 68 61 6c 6c 6f 20 c3 a4 c3 b6 c3 bc>
```

We hit this issue with "stringified" JSON dumps that contained quite a lot of special characters, etc.; the affected files will be truncated and information / data will be lost. So I'd highly recommend to use `buffer.from(str, 'utf-8')` and state this in the respective examples.

**Comment by 5saviahv** [comment]
fixed, thanks
