### ISSUE TITLE
zipEntry.getData().toString('utf8') and \u0000, \u0005 characters (Quarantine file in zip)

### ISSUE THREAD

**Issue by cybercussion** [cthackers/adm-zip#380]
Hi,
I got one XML file that started throwing all these unexpected character.  Near as I can tell the file is us-ascii but I can't figure out why a single file is doing this or if I need to perform further encoding checks on the file.

This is only occurring within a node lambda reading the file 
`let zipData = zipEntry.getData().toString('utf8');`

Then as I feed it in to fast-xml-parser it triggers:
char '\u0005' is not expected. or '\u0000'

**Comment by cybercussion** [comment]
Nevermind, I just found that someone left a weird file in a zip.

2��ATTR��#�#com.apple.quarantineq/0002;57d2cb1b;The\x20Unarchiver;

**Comment by 5saviahv** [comment]
It seems to be binary file if it contains characters like \u0000 and \0005.

If I looked **com.apple.quarantine** it seems to be meta data what mac os creates. Apparently when zip file was created meta data was also included.

This meta data is most common with tar files.

**Comment by cybercussion** [comment]
Looks like it was unzipping but I had a sub process that was parsing XML files and thats where this error appeared to come up.  I filtered it off so I would not attempt to process files like these.  We can close it since it doesn't appear to crash the adm-zip process.
