### ISSUE TITLE
ADM-ZIP: Wrong Password

### ISSUE THREAD

**Issue by 346180990** [cthackers/adm-zip#385]
Add a password to it during decompression, but report an error

Compression mode：
WinRAR compression password addition
password:123456

Decompression mode：
```
    zipEntry.getDataAsync(function (data, err) {
        if (err) {
            console.log(err);
        } else {
            console.log(data);
        }
    }, '123456');
```

**Comment by 346180990** [comment]
The above problem has been solved
But there is a new problem
![image](https://user-images.githubusercontent.com/39411372/126448226-20c6e44a-a8b3-4d00-9caa-7fcf6516360b.png)
Above can be normal decompression
![image](https://user-images.githubusercontent.com/39411372/126448326-b94b7f6c-2e8c-450c-a233-48201ffd247b.png)
But this one can't be decompressed

The two differences are Characteristics:Encrypt Descriptor and NTFS:Encrypt 
How can I solve this problem
thanks

**Comment by 5saviahv** [comment]
Never seen this "Characteristics" in any where in ZIP documentation. Maybe WinRAR uses NTFS encrypt along with zipCrypto. 

Can you try extract it with 7z ?

**Comment by 346180990** [comment]
7z extract is  a normal，It's also normal to use npm Unzipper

**Comment by nab138** [comment]
> Add a password to it during decompression, but report an error
> 
> Compression mode：
> WinRAR compression password addition
> password:123456
> 
> Decompression mode：
> 
> ```
>     zipEntry.getDataAsync(function (data, err) {
>         if (err) {
>             console.log(err);
>         } else {
>             console.log(data);
>         }
>     }, '123456');
> ```

Quick question, how did you solve this? I'm experiencing a similar issue
