### ISSUE TITLE
`extractAllToAsync` callback need to wait for the writing to finish

### ISSUE THREAD

**Issue by zce** [cthackers/adm-zip#389]
v0.5.6

```js
zip.extractAllToAsync(output, true, err => {
  /* istanbul ignore if */
  if (err != null) throw err
  resolve()
})
```

ref: https://github.com/cthackers/adm-zip/blob/3caa15d50b54d19a2212a11b5a6c86d89caa4a77/adm-zip.js#L668

**Comment by KevinAo22** [comment]
Agreed.
The callback should wait all extracting tasks finished. And then it could be converted to the modern promise friendly, using promisify.

**Comment by KevinAo22** [comment]
#393 I submit a PR to fix it. 
Hope it works.

**Comment by 5saviahv** [comment]
Yes It seems to work, nice work.

I merged PR, but I dont have access to npm.

**Comment by dscalzi** [comment]
I'm pretty sure this changing is causing the callback to never trigger now. An operation that was working now hangs indefinitely.

**Comment by KirrsGool** [comment]
https://github.com/cthackers/adm-zip/issues/407#issuecomment-990086783) - a workaround
