### ISSUE TITLE
[feature request] Pass fs to use to constructor

### ISSUE THREAD

**Issue by riccardomoja** [cthackers/adm-zip#391]
It would be great if constructor get optional parameter "fs", instead of having just Utils.fileSystem.require.
If not provided, AdmZip works just like now.
If provided, AdmZip should use received fs. It would be great for unit testing functions that  use AdmZip, with some kind of memory fs (assuming passed fs implements the same interface as node), such as memfs

**Comment by cthackers** [comment]
Done.
There is now a `fs` in the provided option object that let's you mock the default fs

**Comment by riccardomoja** [comment]
First of all, thank you.
Unfortunately it seems not to work correctly.
Now I can provide mocked fs to constructor, but it seems that is still used node fs in functions such as `writeFileTo` in util.js
Maybe I'mwrong , ma could be because of this :
`const fs = require("./fileSystem").require();`
that provides just nodejs fs or original-fs, but it's not considering the  mocked one
