### ISSUE TITLE
Please start tagging git/npm issues correctly.

### ISSUE THREAD

**Issue by tabarra** [cthackers/adm-zip#395]
I'm having a few issues with this library, and is very hard for me to see what changed from version to version if the npm and git tags don't match.  
For instance, I'm currently on v0.5.6 and the latest npm package is v0.5.9, which doesn't even have a tag in here.  
How am I suppose to find out what changed? How am I supposed to try to help you guys fix those issues?

**Comment by barryhagan** [comment]
And please start using semver properly.  You made breaking changes between 0.5.6 and 0.5.7 with this commit causing extracted files to no longer maintain the existing permissions: https://github.com/cthackers/adm-zip/commit/2b2a1d79eb6337cd597ab4d5fac8d1f322dc330c

**Comment by devsibwarra** [comment]
@iacobnasca @5saviahv sorry to ping, but you've both created tags on this repo before

Trying to identify the version boundaries, I think this is "close"
* [v0.5.6 to v0.5.7](https://github.com/cthackers/adm-zip/compare/v0.5.6...c1236b5)
* [v0.5.7 to v0.5.8](https://github.com/cthackers/adm-zip/compare/c1236b5...d77f1cf4)
* [v0.5.8 to v0.5.9](https://github.com/cthackers/adm-zip/compare/d77f1cf4...bebbabf)

If that feels correct, making repo tags would be
```
git tag -a v0.5.7 -m 'v0.5.7' c1236b5
git tag -a v0.5.8 -m 'v0.5.8' d77f1cf4
git tag -a v0.5.9 -m 'v0.5.9' bebbabf
```

**Comment by 5saviahv** [comment]
missing tags added
