### ISSUE TITLE
Is there a limit to the file size?

### ISSUE THREAD

**Issue by coderLanlan** [cthackers/adm-zip#429]
I use it to read a big zip file（2.6GB），it prompts an error：File size (2689810164) is greater than 2 GB 

vision：^0.5.9

code：
try {
  const zip = new admZip(`${cases}/${params.name}.zip`)
    let cacheObj: any = zip.readAsText(`cache.txt`)
} catch(err) {
  console.log(err)
}

**Comment by Arkellys** [comment]
Duplicate of #334

**Comment by coderLanlan** [comment]
thanks
