### ISSUE TITLE
SIDE EFFECT: after toBufferPromise call, the zip file that toBufferPromise was called on is EMPTY

### ISSUE THREAD

**Issue by bennettellis** [cthackers/adm-zip#440]
This is not expected behavior nor documented. Is this correct?
```
zip1 = new AdmZip(null);
await zip1.addZipComment("ZIP1");
await zip1.addFile("iac/", null);
await zip1.addFile("iac/file1.txt", Buffer.from("some text"));

console.log(zip1.getEntries()); // will return array[2]

const zip1Buff = await zip1.toBufferPromise();

console.log(zip1.getEntries()); // will return array[0]
```

**Comment by bennettellis** [comment]
I believe this is because `zipFile.toAsyncBuffer` is using `Array.pop` to navigate the entries in the zip, thereby removing them during iteration. Again, is this the intended behavior (which renders the zip file useless after `toBufferPromise` or other methods that call toAsyncBuffer are called. It seems very counterintuitive, and it's not clear why `Array.pop` method was used rather than another array iteration method that doesn't have side effects.

**Comment by 5saviahv** [comment]
should be fixed now
