### ISSUE TITLE
File not added in folder zip using addLocalFolder

### ISSUE THREAD

**Issue by rusel-arceo** [cthackers/adm-zip#441]
I am tried to include a folder with all theirs subfolder and fiiles, I use this:
**
const zip = new AdmZip();
      zip.addLocalFolder(pathToCompress);
      zip.writeZip(pathDestinity);   
**

and a structure to compress like:

![image](https://user-images.githubusercontent.com/67992212/214115940-1035f037-7484-42ce-a3a5-19964965cc51.png)

but in the file compress, the file.csv is no added.

is this a trouble or there is a way to added all the content included files ?

I've found in documentation and I had not found nothing.

**Comment by 5saviahv** [comment]
Based on OP example:
* if you specify "subfolder2" it will include "file.csv". 
* if you specify "subfolder3" it will not include "file.csv".
