### ISSUE TITLE
addFile creating directory structure if filename contains '/'

### ISSUE THREAD

**Issue by b-hexsoul** [cthackers/adm-zip#446]
I am adding files to a zip and their filename is the product name. Some of these product names contain '/' for example:
1025/1038 - Developer

This creates a directory in the zip:
/1025
- /1038 - Developer.pdf

**Comment by renekoch** [comment]
'/' is not a valid charater in filenames

**Comment by GavinThomas1192** [comment]
This can un-intentionally create folder nesting without that being the intention. When creating files based on dynamic data, it would be important to note, that you must remove the '/' from the name.

**Comment by 5saviahv** [comment]
Zip format uses `'/'` as a main directory separator and it does not matter what OS is used.

Only some very early versions of `pkzip` used `'\'` as separator.
Both are `reserved` making it more compatible for different OS'es.
