### ISSUE TITLE
Different bag sizes,Windows is 12.78MB;this is 12.86MB

### ISSUE THREAD

**Issue by jiesir** [cthackers/adm-zip#460]
Why is packaging larger than packaging in Windows?
The default packaging tool for the same folder using Windows is 12.78MB,
After using adm zip, the package size is 12.86MB.
Boss, is there a way to solve it?

**Comment by cthackers** [comment]
What did you compress? If you try to compress jpegs for example which are already compressed, they will not compress at all. It will only become larger because of the additional headers. So it depends lots on what are you archiving not on OS

**Comment by 5saviahv** [comment]
can't say since there is no relevant information available.

If file was re-compressed then it might be compression algorithm implementation differences.
