### ISSUE TITLE
npm install fail

### ISSUE THREAD

**Issue by jankin-l** [cthackers/adm-zip#461]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for string-width-cjs@4.2.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@isaacs/cliui'
npm ERR! notarget

**Comment by 5saviahv** [comment]
it seems to be npm issue

**Comment by henrylin03** [comment]
> it seems to be npm issue

hi, how was this fixed?

**Comment by 5saviahv** [comment]
ETARGET error means you specified package what is not available or version what isn't actually available in npm repository.

you can  check available versions like so:
`npm show adm-zip versions`
