### ISSUE TITLE
High usage of RAM while extracting archive

### ISSUE THREAD

**Issue by dschwarz1989** [cthackers/adm-zip#47]
I am currently writing on a tool to unzip archives using your module and I just recognised the very heavy usage of RAM.
To extract an archive of about 11MB, my node.exe uses about 250MB of RAM.
I experienced this with Node v0.10.5 on different machines running Windows7 or Windows8 using different archives of nearly the same size in total (might have been a few KB more or less on different archives), and with files of different filesizes within the archives (between 1KB and 1.8MB per file), the RAM-usage has always been nearly the same.

My code:

var AdmZip = require('adm-zip');

var archivePath = 'any-path.zip';
var extractPath = 'another-path';

var zip = new AdmZip(archivePath);
zip.extractAllTo(extractPath);

**Comment by melroy89** [comment]
Follow-up: #417
