### ISSUE TITLE
Password validation failing for valid passwords, on files where bit 3 of general purpose flag is set.

### ISSUE THREAD

**Issue by lukemalcolm** [cthackers/adm-zip#471]
I'll shortly be putting in a Pull Request to fix the below, but I'm logging an issue for tracking purposes.

Currently, ADM-ZIP ZipCrypto (PKCRYPT method) rejects valid passwords that use the Info-Zip standard of password validation.

This specification uses the high bit of the headers modified time, instead of the crc to compare against the LSB of the decrypted 12 bit salt and is only applicable when bit 3 of the general purpose bit flag is set.

This method of password checking looks like it originated in the Info-Zip standard, is still used by a number of older zip generators and is gracefully handled by all other zip tools I tried (7zip, WinZip, Windows etc).

Spec References:

[Info-Zip Standard](https://libzip.org/specifications/appnote_iz.txt) - Line 2806
[minizip-ng implementation](https://github.com/zlib-ng/minizip-ng/blob/master/mz_zip.c) - Line 193

In my particular case, this has occurred in zips generated [zlib-ng/minizip-ng](by https://github.com/zlib-ng/minizip-ng).

This may be the cause of #467 #385 - but without more details, it's hard to say.

More details in the forthcoming Pull Request.

**Comment by lukemalcolm** [comment]
Have added a pull request #472

**Comment by dhirajkumar7029** [comment]
I am facing the same error.

I have merged the above PR changes into my local repo and checked. It's working. @lukemalcolm Can we expedite in pushing the above fix?

**Comment by lukemalcolm** [comment]
The pull request #472 was merged into 0.5.11. Closing this issue.
