### ISSUE TITLE
If "Created Time", "Modified Time", or "Accessed Time" are the start of the 1979 epoch, an out of range exception is thrown.

### ISSUE THREAD

**Issue by TheRedstoneScientist** [cthackers/adm-zip#485]
After some investigation, I have figured out what went wrong for me. Hopefully this will help others. The issue in my case was that the "LastModifiedTime" and "CreatedTime" were the default 1979 timestamps. I used BulkFileChanger (https://www.nirsoft.net/utils/bulk_file_changer.html) to edit all my files to have a new time. This fixed it for me. 
This happened because I copied items directly from another archive without unzipping first.
I figured this out by observing the exception happen on line 256. 
![image](https://github.com/cthackers/adm-zip/assets/7861984/484cd8ae-2318-426f-a351-bc7635b22827)

_Originally posted by @TheRedstoneScientist in https://github.com/cthackers/adm-zip/issues/426#issuecomment-2074912745_

**Comment by roosipuu** [comment]
yes, ZIP uses MSDOS epoch 1/1/1980 and javascript does use UNIX epoch 1/1/1970

most likely value is negative.
