### ISSUE TITLE
Issue with canonical function handling filenames containing Windows style double slash

### ISSUE THREAD

**Issue by g1f9** [cthackers/adm-zip#486]
## Description:
I have encountered an issue with the 'canonical' function when dealing with filenames that contain Windows style double slash paths.

## Here is an example:
My original file path was
'source/functions/nodejs/D:\\Users\\Downloads\\img\\qrcode.png'

Upon being processed by the canonical function, the output was transformed to:
'/source/functions/nodejs/D:/Users/Downloads/img/qrcode.png'

It seems the canonical function isn't handling the double slash correctly, as the output does not match my expectations.

## source code
https://github.com/cthackers/adm-zip/blob/bd83f197f4a376f3996706d6522588f025b2fc32/util/utils.js#L210

Any assistance on this matter would be greatly appreciated.

**Comment by roosipuu** [comment]
Can you explain what were your expectations ?

From your example:
Under windows it generates path:
>``'source\\functions\\nodejs\\D:\\Users\\Downloads\\img\\qrcode.png'``
>It does fail since there is forbidden character ":" in path

Under Linux it generates path:
>'source/functions/nodejs/D:/Users/Downloads/img/qrcode.png'
>It is completely acceptable path

Even when in posix systems backward slashes are safe to use in file and folder names. It is recommended not to use them so. Also this library have to work in windows machines as well, where they are not acceptable in file names and even allows to open a vector for attacking the systems.

**Comment by 5saviahv** [comment]
Not enough information at the moment.

I close it for now, if anyone can add more information they can open new issue or add it below.
