### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE] if expectedLength is 0 in methods/inflater.js

### ISSUE THREAD

**Issue by jo-sirin** [cthackers/adm-zip#496]
Hi
There is an issue coming up with 0.5.13 (commit 689b300): For nodejs v18, in line 9 of file methods/inflater.js, parameter "option" must not contain a "maxOutputLength" of value 0 - otherwise node:zlib throws a RangeError.

The fix seems to be easy, e.g. change in methods/inflater.js:5 "version >= 15" to "version >= 15 && expectedLength > 0".

Cheers, Joachim

**Comment by cthackers** [comment]
cool. thanks. it's fixed and released
