### ISSUE TITLE
Broken chrome builtin unpackaging compatibility

### ISSUE THREAD

**Issue by skoniks** [cthackers/adm-zip#497]
I don't consider myself an expert on working with zip archives, but i detected that commit https://github.com/cthackers/adm-zip/commit/9c37fa86d1410bb917dd5f5da4dbc013918633e5 brokes compatibility with chrome extension unpackaging compatibility on windows (may be not only on windows).

Attempting to install archived extension you receive an error and temporary extracting folder looks like this:

![image](https://github.com/cthackers/adm-zip/assets/13507597/8a788aef-817e-4c0d-9130-03de1da151e1)

**Comment by skoniks** [comment]
`Utils.canonical` replaces backslash to slash, that somehow broken archive extraction

![image](https://github.com/cthackers/adm-zip/assets/13507597/d8d76384-82c4-4657-8cf9-4aa1d5e934ac)

**Comment by 5saviahv** [comment]
Interesting, APPNOTE says _you should use `slash`_, but `backslashes` are also permitted in zip files.

idea for adding function there is avoid constructing file names like `..\..\..\windows\system32\drivers\etc\hosts`
I have some zip archives created in windows with tools like 7z, WinZIP and they all use slashes.

but I think if chrome really uses backslashes we should add option like `useBackslash`.

**Comment by skoniks** [comment]
> Interesting, APPNOTE says _you should use `slash`_, but `backslashes` are also permitted in zip files.
> 
> idea for adding function there is avoid constructing file names like `..\..\..\windows\system32\drivers\etc\hosts` I have some zip archives created in windows with tools like 7z, WinZIP and they all use slashes.
> 
> but I think if chrome really uses backslashes we should add option like `useBackslash`.

As i mentioned before, problem is specific for creating archive on windows, broken archives cause error in all desktop browsers (Opera, Edge, Firefox and others, not only Chrome) for windows and mac. I tried creating the same archive with same pkg version from mac and it do not cause any errors. So i conclude that the `problem is specific only for windows`, not for browsers.

**Comment by skoniks** [comment]
> `Utils.canonical` replaces backslash to slash, that somehow broken archive extraction

After some research promlem was opposite in replacing shashes on backslashes, `Utils.canonical` uses POSIX `pth.posix.normalize`, and then uses non POSIX `pth.join` that leads to an error
