### ISSUE TITLE
addLocalFile does not add the ".env" file to the archive

### ISSUE THREAD

**Issue by galleonsZcc** [cthackers/adm-zip#519]
`const zip = new AdmZip();`
`zip.addLocalFolder('server', 'server');`
`zip.addLocalFile('.env');`
`zip.writeZip('archive.zip');`

there is no file .env in the zip

**Comment by 5saviahv** [comment]
I cannot replicate the issue:
I am using Node 16 and old Linux

and it seems to work well.

[archive.zip](https://github.com/user-attachments/files/16185719/archive.zip)
