### ISSUE TITLE
`getEntries`/`getEntry` no longer read files in folder on archives created with version >= `0.5.13`

### ISSUE THREAD

**Issue by Arkellys** [cthackers/adm-zip#521]
A bug was introduced on version `0.5.13` which affect reading files inside folders. I only tested the methods `getEntries()` and `readFileAsync()` (which uses `getEntry()`), but I suppose this bug does not affect only these two. Here are some test cases:

Whether I test on `v0.5.12` or `v0.5.13`:

- For an archive created with `v0.5.12`
  - `getEntries()` -> returns root files + files in folder, with `entryName` as: `folder/file.jpg`
  - `getEntry()` -> works as expected

- For an archive created with `v0.5.13`
  - `getEntries()` -> returns root files + files in folder, with `entryName` as: `folder\\file.jpg`
  - `getEntry()` -> returns an error (via `readFileAsync()`): `getEntry failed for:folder/file.jpg`

Additionnaly, I can see that for both archives all the files and folderd are here and with the correct names. Extracting all works as expected.

Something messing up the paths?

--

Versions:
- Node v20.9.0
- Windows 10

**Comment by Arkellys** [comment]
I'm not sure the version matches, but maybe it has something to do with the change on [this commit](https://github.com/cthackers/adm-zip/commit/85d28e2b036d3803b16c003dcf98732b80a1bb82?diff=unified&w=0#diff-ce58b03dc27c53e24ea7ec3b41e184944d4bb0164b268c6ef82d83a03228a893L299)? It looks like a Window fix has been removed but is not covered by the new code.

**Comment by jcompagner** [comment]
we have the same problem, suddenly the entries that are created i guess on windows are give the \ in the path/name
So suddenly i have to get the entry also by a \ (or compare it my self)
I think this is wrong, all other tools will always use the forward slash.

**Comment by 5saviahv** [comment]
It is related with #497 and #512 and fixed in repo, but it is not released by @cthackers yet.

**Comment by cthackers** [comment]
It's released now!

**Comment by Arkellys** [comment]
I just tested and this issue is solved with `v0.5.15`, thank you.
