### ISSUE TITLE
deleteFile erase more files than expected

### ISSUE THREAD

**Issue by matteo-cristino** [cthackers/adm-zip#523]
To reporduce the issue create a folder with the following form
```
test
├── path1
│   ├── file1.txt
│   └── folder1
│       └── file2.txt
└── path2
    ├── file1.txt
    └── folder1
        └── file2.txt
```
create a zip, for example on linux terminal with
```sh
zip -r test.zip test
```
Now run the following code
```js
import AdmZip from "adm-zip";

let zip = new AdmZip("./test.zip");

console.log("* Before delete of test/path1/:");
zip.getEntries().forEach((entry) => {
  console.log(entry.entryName);
});

zip.deleteFile("test/path1/");

console.log("");
console.log("* After delete of test/path1/:");
zip.getEntries().forEach((entry) => {
  console.log(entry.entryName);
});
```
The result will be
```
* Before delete of test/path1/:
test/
test/path2/
test/path2/file1.txt
test/path2/folder1/
test/path2/folder1/file2.txt
test/path1/
test/path1/file1.txt
test/path1/folder1/
test/path1/folder1/file2.txt

* After delete of test/path1/:
test/
test/path2/
test/path2/file1.txt
test/path2/folder1/
```
As it can be seen during the deletion of `/test/path1/` also `/test/path2/folder1/file2.txt` has been eliminated. 

I have not debugged it to much, but from a first look to me it is that in the deleteFile function, in particular when eliminating the entry from the entryList [here](https://github.com/cthackers/adm-zip/blob/master/zipFile.js#L221), the entry is not found and thus `indexOf` will return `-1` that causes the elimination of the last element of the array.

**Comment by 5saviahv** [comment]
Hmm, it seems there is error when deleting folders with multiple levels deep.

File is already deleted and searcing its location with IndexOf returns -1. Since there is no value check, it will simply delete last entry.

**Comment by matteo-cristino** [comment]
Thank you very much for the quick fix! 🎉

Do you know when a new release will be done to have this bug fixed?

**Comment by 5saviahv** [comment]
fix should be in last release
