### ISSUE TITLE
ReferenceError: totalEntries is not defined.

### ISSUE THREAD

**Issue by sidartaveloso** [cthackers/adm-zip#534]
**totalEntries** was not declared, throwing error at this line.
to fix, I just put let at begin in this line.

let totalEntries = 0;

this situation was introced at this comit:

https://github.com/cthackers/adm-zip/blame/161a61f2283b96bbe692a7c5d232787636e8b3bc/zipFile.js#L259

**Comment by olafurpg** [comment]
I am hitting on the same issue. I am unable to reproduce after downgrading to 0.5.10.

**Comment by riderx** [comment]
Same here
