### ISSUE TITLE
Can't show filename normal

### ISSUE THREAD

**Issue by huyinghuan** [cthackers/adm-zip#75]
when the file name is Chinese ,it  can't display properly

**Comment by jocool** [comment]
Same issue on my side with utf-8 chars like é, à or ê ....

any hint on how to fix this issue?

**Comment by huyinghuan** [comment]
＠jocool  No. I gave up.

**Comment by vp-npetrini** [comment]
Hi there,

I face the same issue with chars like é, à, etc...

Is there a fix on the way or a workaround to this problem ?

**Comment by jocool** [comment]
I've not found a solution yet ... no time to investigate ... if you find a solution please update the answer here ... i'll do the same

**Comment by payflix** [comment]
Same problem here, always showing ����

**Comment by veresnikov** [comment]
+ same problem

**Comment by wangdahoo** [comment]
should be done like this, take chinese encoding for example:

```js
const AdmZip = require('adm-zip')
const iconv = require('iconv-lite')
const zip = new AdmZip('path/to/your/zip/file')

zip.getEntries().forEach(entry => {
    entry.entryName = iconv.decode(entry.rawEntryName, 'gbk')
    console.log(entry.entryName)
})

zip.extractAllTo('path/to/extract')
```

**Comment by 712163** [comment]
> should be done like this, take chinese encoding for example:
> 
> ```js
> const AdmZip = require('adm-zip')
> const iconv = require('iconv-lite')
> const zip = new AdmZip('path/to/your/zip/file')
> 
> zip.getEntries().forEach(entry => {
>     entry.entryName = iconv.decode(entry.rawEntryName, 'gbk')
>     console.log(entry.entryName)
> })
> 
> zip.extractAllTo('path/to/extract')
> ```

good job
