### ISSUE TITLE
GPL code in the project

### ISSUE THREAD

**Issue by eddiemonge** [cthackers/adm-zip#77]
Any chance of removing the GPL'ed code (deflater.js) or go back to using custom written functions?

**Comment by jlamondw** [comment]
+1

**Comment by luano** [comment]
deflater.js still contains GPL covered code, and therefore the license for adm-zip should be GPL.

**Comment by RodolpheGohard** [comment]
+1

**Comment by christian-blades-cb** [comment]
So... soon still?

**Comment by bleggett** [comment]
Since these licenses cannot be legally mixed, this is a legal problem, and one that is creating problems for those of us using node packages in a corporate environment.

**Comment by csantanapr** [comment]
@bleggett 
   Here are some alternatives with MIT license 

https://github.com/archiverjs/node-zip-stream
https://github.com/archiverjs/node-archiver.git

**Comment by hannsjohn2007** [comment]
Hi cthackers,

I read your reply 'Yes soon' I assume that you will remove the 'deflater.js' is this still ongoing.? since we have legal problems about your package. hope for your fast response.

**Comment by scanlime** [comment]
+1

**Comment by TerryAspen** [comment]
It has been almost 5 years since it was mentioned that this would be addressed soon. Is this still on anyone's radar for resolution? Unfortunately we cannot use it currently with a GPL file included.

**Comment by achrinza** [comment]
Any updates on this? This issue has been quite problematic at our end too.

**Comment by michaelfarrell76** [comment]
i think this has been fixed since deflater was the issue and it no longer has the GPL comment: https://github.com/cthackers/adm-zip/blob/master/methods/deflater.js

can this issue be closed?

**Comment by 5saviahv** [comment]
currently adm-zip uses node.js zlib module for deflate/inflate
