### ISSUE TITLE
Invalid CEN header (bad signature) without Japanese chars..

### ISSUE THREAD

**Issue by marvinosswald** [cthackers/adm-zip#83]
I've got this error :( don't know why..

My Code:
`
            var zip = AdmZip(new Buffer(data, 'binary'));
                zip.extractAllTo(__dirname + '/ghosts/' + path +'/',true);
`

Any Ideas ? 

Cheers Marvin

**Comment by cam5** [comment]
I had the same issue as @marvinosswald, just want to paste my fix. The problem was reading the file before it had finished streaming in to the buffer.

    const recievedFile = fs.createWriteStream('/recievedFile.zip');
    request('/url-returning-a-zip').pipe(recievedFile);

    recievedFile.on('close', () => {
      const bits = fs.readFileSync('/recievedFile.zip');
      const zip = new AdmZip(bits);
    });
