### ISSUE TITLE
Entry doesn't exist when extract chrome-win32.zip

### ISSUE THREAD

**Issue by rayou** [cthackers/adm-zip#89]
Zip file: http://commondatastorage.googleapis.com/chromium-browser-snapshots/Win/262048/chrome-win32.zip

I want to extract the root folder `chrome-win32` by this command.
`zip.extractEntryTo("chrome-win32/", "./test", false, true);`

but the result shows...
`Entry doesn't exist`

then I realize that the folder `chrome-win32` is not a entry to this zip file.

is there any way that I can extract all files in the `chrome-win32` folder to specific folder?

**Comment by 5saviahv** [comment]
Seems to working
